package ru.venusgames.pavel.dreadfulyard.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import ru.venusgames.pavel.dreadfulyard.database.Contact;
import ru.venusgames.pavel.dreadfulyard.database.PhoneNumber;
import ru.venusgames.pavel.dreadfulyard.database.Message;

import ru.venusgames.pavel.dreadfulyard.database.ContactDao;
import ru.venusgames.pavel.dreadfulyard.database.PhoneNumberDao;
import ru.venusgames.pavel.dreadfulyard.database.MessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contactDaoConfig;
    private final DaoConfig phoneNumberDaoConfig;
    private final DaoConfig messageDaoConfig;

    private final ContactDao contactDao;
    private final PhoneNumberDao phoneNumberDao;
    private final MessageDao messageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        phoneNumberDaoConfig = daoConfigMap.get(PhoneNumberDao.class).clone();
        phoneNumberDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        contactDao = new ContactDao(contactDaoConfig, this);
        phoneNumberDao = new PhoneNumberDao(phoneNumberDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);

        registerDao(Contact.class, contactDao);
        registerDao(PhoneNumber.class, phoneNumberDao);
        registerDao(Message.class, messageDao);
    }
    
    public void clear() {
        contactDaoConfig.getIdentityScope().clear();
        phoneNumberDaoConfig.getIdentityScope().clear();
        messageDaoConfig.getIdentityScope().clear();
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

    public PhoneNumberDao getPhoneNumberDao() {
        return phoneNumberDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

}
