package ru.venusgames.pavel.dreadfulyard.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MESSAGE".
 */
public class Message {

    private Long id;
    private String messageChatId;
    private String messageUserId;
    private String messageMessageId;
    private String messageType;
    private Integer messageStatus;
    private String messageData;
    private java.util.Date messageTimeStamp;

    public Message() {
    }

    public Message(Long id) {
        this.id = id;
    }

    public Message(Long id, String messageChatId, String messageUserId, String messageMessageId, String messageType, Integer messageStatus, String messageData, java.util.Date messageTimeStamp) {
        this.id = id;
        this.messageChatId = messageChatId;
        this.messageUserId = messageUserId;
        this.messageMessageId = messageMessageId;
        this.messageType = messageType;
        this.messageStatus = messageStatus;
        this.messageData = messageData;
        this.messageTimeStamp = messageTimeStamp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMessageChatId() {
        return messageChatId;
    }

    public void setMessageChatId(String messageChatId) {
        this.messageChatId = messageChatId;
    }

    public String getMessageUserId() {
        return messageUserId;
    }

    public void setMessageUserId(String messageUserId) {
        this.messageUserId = messageUserId;
    }

    public String getMessageMessageId() {
        return messageMessageId;
    }

    public void setMessageMessageId(String messageMessageId) {
        this.messageMessageId = messageMessageId;
    }

    public String getMessageType() {
        return messageType;
    }

    public void setMessageType(String messageType) {
        this.messageType = messageType;
    }

    public Integer getMessageStatus() {
        return messageStatus;
    }

    public void setMessageStatus(Integer messageStatus) {
        this.messageStatus = messageStatus;
    }

    public String getMessageData() {
        return messageData;
    }

    public void setMessageData(String messageData) {
        this.messageData = messageData;
    }

    public java.util.Date getMessageTimeStamp() {
        return messageTimeStamp;
    }

    public void setMessageTimeStamp(java.util.Date messageTimeStamp) {
        this.messageTimeStamp = messageTimeStamp;
    }

}
